### ISSUE TITLE
공연 구현

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-service#2]
# Description

티켓 예약을 위한 "공연"

그에 관련된 최소 기능 구현

# To do
- 공연 데이터 구조 설계 (최소: pk, name, reservetion-limit-integer)
- get one / get many
- sidejob: Mock Data 세팅 스크립트 (fakerjs 등 참고)
- 실제 DB를 사용하지 않아도 됩니다. (Mockup test only)

# Test Checklist

**Comment by junha-ahn** [comment]
공연 도메인의 이름을 간단하게 공연으로 할지 고민해주세요.

공연, 음악회, 전시회 등 인터파크에 티켓팅 가능한 다양한 service 들을 한번에 묶을 수 있을까요? 

묶는다면 이름은 어떻게 될까요?

**Comment by hihahayoung** [comment]
> 공연 도메인의 이름을 간단하게 공연으로 할지 고민해주세요.
> 
> 공연, 음악회, 전시회 등 인터파크에 티켓팅 가능한 다양한 service 들을 한번에 묶을 수 있을까요?
> 
> 분명 모두 예매의 대상이 된다는 점에서 같은 데이터입니다.
> 
> 묶는다면 이름은 어떻게 될까요?

만약 묶는다면 이름으로 event 제안해 봅니다.

**Comment by hihahayoung** [comment]
performance도 무리는 없을 것 같지만 전시 같은 경우는 perform하는 게 아니라 굳이 따지자면 event가 더 적합해 보이네요!
