### ISSUE TITLE
로그인/인증 흐름도 작성

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-service#35]
# Description

현재 #30 에서 구현한 로그인 과정에 대한 다이어그램을 만들어주세요

또한 이번주 토요일(`2023.07.22`) 발표 부탁드립니다.

내용은 로그인 처리 및 인증 과정에 대한 전반 (JWT Token, Spring security, Filter 등)
- 그 외 포함하고 싶은 내용

# To do
- 한개 이상의 로그인/인증 흐름도 작성
- 발표 준비

# Example

다이어그램 툴
- [Excalidraw](https://hattbatt.tistory.com/entry/%EA%B0%9C%EB%B0%9C%EC%9E%90-%EB%8B%A4%EC%9D%B4%EC%96%B4%EA%B7%B8%EB%9E%A8-%ED%88%B4-%EC%B6%94%EC%B2%9C-Excalidraw)
- [TOP 다이어그램 툴 8종](https://careerly.co.kr/comments/78482)

다이어그램 키워드
- API Flow Chart
- UML 

![image](https://github.com/f-lab-clone/ticketing-service/assets/41976906/310f3f4d-0e4f-405a-8897-2c94e7129ed0)
> [from](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow)

![image](https://github.com/f-lab-clone/ticketing-service/assets/41976906/b9ec3575-fcf7-449d-a148-2ada031e74b2)
> [from](https://velog.io/@tkppp-dev/SpringBoot-JWT-Spring-Security-%EB%A1%9C%EC%BB%AC-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)

![image](https://github.com/f-lab-clone/ticketing-service/assets/41976906/d0d16672-6de4-4bba-bc1a-73a48d693478)
> [from](https://velog.io/@seongwon97/Spring-Boot-Authentication%EC%9D%98-%EA%B5%AC%EC%A1%B0)

**Comment by minjun3021** [comment]
![image](https://minjun3021.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fcbc92283-a699-4e16-ba61-07530063c000%2FUntitled.png?table=block&id=409df365-6468-49f7-b471-945d3518f509&spaceId=dba8566d-40ff-4dfb-b737-7d040826775b&width=2000&userId=&cache=v2)

> [from](https://minjun3021.notion.site/Spring-Security-JWT-5c7c9a7771e147a6bde81bc1cbcf46de)
