### ISSUE TITLE
CI: 코드 컨벤션 체크

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-service#6]
# Description

코드 컨벤션 체크를 위한 툴을 적용해주세요 (린트, 컨벤션 체크)

# To do
- git actions와 intellij 모두 동작해야합니다. 
- git actions와 intellij 에서 각각의 설정 파일이 존재하는게 아니라, 공통의 설정파일을 이용해주세요.
- intellij 환경에서는 formet check와 lint 작업을 모두
- git acitons에서는 최종적으로 format check 결과가 출력되도록 해주세요 (만약 convention을 준수하지 않았다면 오류 메시지 등을 출력해서 PR approve에 정보를 부탁드립니다)
  - 가정) 모든 개발자가 intellij 환경을 쓰지 않으며, 모든 개발자가 lint를 개발단계에서 적용하지 않는다는 가정하에 git actions에 해당 기능을 구현합니다.

# Test Checklist

**Comment by bohblue2** [comment]
Local dev env에선 동작하게끔 했습니다만, Github Action에서 ktlint workflow 파일이 PR시마다 안 돌아가는 이유를 모르겠습니다. 리뷰바람.

**Comment by junha-ahn** [comment]
[klint-actions](https://github.com/f-lab-clone/ticketing-service/actions/runs/5486775198/jobs/9997311678)에서는 성공했다고 뜹니다. 

#11 PR을 제가 닫았기때문에, 해당 브랜치가 main으로 합쳐지지 않았고, 그렇기 때문에 모든 PR마다 안돌아갑니다.

commit template 준수해서 다시 올려주세요.

**Comment by junha-ahn** [comment]
[jobs](https://github.com/f-lab-clone/ticketing-service/actions/runs/5486775198/jobs/9997311678) 중 `klint` 부분에서 아래와 같은 메세지 뜨는데 확인 부탁드립니다.

```bash
reviewdog: This GitHub token doesn't have write permission of Review API [1], 
reviewdog: Reporting results for "ktlint"
so reviewdog will report results via logging command [2] and create annotations similar to
github-pr-check reporter as a fallback.
[1]: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target, 
[2]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands
reviewdog: No results found for "ktlint". 34 results found outside diff.
```

**Comment by junha-ahn** [comment]
assigned @junha-ahn

**Comment by junha-ahn** [comment]
reference 
- [Kotlin + Spring 시작하기(2) - Kotlin Lint](https://velog.io/@eastperson/Kotlin-Spring-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B02-Kotlin-Lint#overview)
- [깔끔한-포맷팅을-위한-ktlint-적용하기-feat-kotlin](https://msyu1207.tistory.com/entry/%EA%B9%94%EB%81%94%ED%95%9C-%ED%8F%AC%EB%A7%B7%ED%8C%85%EC%9D%84-%EC%9C%84%ED%95%9C-ktlint-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-feat-kotlin#toc-%F0%9F%9A%80%20ktlint%20with%20gitAction)

**Comment by junha-ahn** [comment]
closed by #17
